version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: apollonia-postgres
    environment:
      POSTGRES_USER: apollonia
      POSTGRES_PASSWORD: apollonia
      POSTGRES_DB: apollonia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apollonia"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
