---
name: Performance Benchmarks

on:
  schedule:
    # Run at 2 AM UTC on Sundays
    - cron: '0 2 * * 0'
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '**/*.py'
      - 'benchmarks/**'
      - '.github/workflows/benchmarks.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmarks:
    name: Performance Benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      deployments: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for benchmark comparisons

      - name: 🔧 Setup Python environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: '3.12'
          install-just: true
          cache-key-prefix: benchmarks

      - name: 💾 Cache benchmark data
        uses: actions/cache@v4
        with:
          path: |
            .benchmarks
            benchmark-results.json
          key: benchmark-data-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            benchmark-data-${{ runner.os }}-

      - name: 🔧 Fix pytest-benchmark compatibility
        run: |
          # Downgrade pytest-benchmark to 4.0.0 for JSON compatibility
          # Version 5.x has a known serialization issue
          uv pip install pytest-benchmark==4.0.0

      - name: ⚡ Run performance benchmarks
        timeout-minutes: 20
        run: just test-benchmarks

      - name: 📊 Store benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        if: always() && hashFiles('benchmark-results.json') != ''
        with:
          tool: 'pytest'
          output-file-path: benchmark-results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          comment-on-alert: true
          summary-always: true
          alert-threshold: '150%'
          fail-on-alert: true
          benchmark-data-dir-path: '.benchmarks'

      - name: 📤 Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-results
          path: |
            benchmark-results.json
            .benchmarks/
